services:
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
    - /opt/docker/postgres/bank:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bank
    ports:
    - "5432:5432"
