services:
  db_dev:
    image: postgres:alpine
    restart: always
    volumes:
    - postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bank
    ports:
    - "5432:5432"

volumes:
  postgres:
