services:
  bank-api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    depends_on:
    - db
    ports:
    - "3000:3000"
    environment:
      APP_PORT: 3000
      POSTGRES_URL: postgres://postgres:1234@localhost:5432/bank?sslmode=disable
      JWT_SECRET_KEY: my_secret

  db:
    image: postgres:alpine
    restart: always
    volumes:
    - postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bank
    ports:
    - "5432:5432"

volumes:
  postgres:
