// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID       int64       `json:"id"`
	UserID   int64       `json:"user_id"`
	Currency interface{} `json:"currency"`
	// should be positive
	Balance   int64              `json:"balance"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Entry struct {
	ID        int64              `json:"id"`
	AccountID int64              `json:"account_id"`
	Amount    int64              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Transfer struct {
	ID          int64 `json:"id"`
	AccountFrom int64 `json:"account_from"`
	AccountTo   int64 `json:"account_to"`
	// should be positive
	Amount    int64              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                int64              `json:"id"`
	FullName          string             `json:"full_name"`
	Email             string             `json:"email"`
	HashedPassword    string             `json:"hashed_password"`
	PasswordChangesAt pgtype.Timestamp   `json:"password_changes_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
