// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transfer.sql

package db

import (
	"context"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (account_from, account_to, amount)
VALUES ($1, $2, $3)
RETURNING id, account_from, account_to, amount, created_at
`

type CreateTransferParams struct {
	AccountFrom int64 `json:"account_from"`
	AccountTo   int64 `json:"account_to"`
	Amount      int64 `json:"amount"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer, arg.AccountFrom, arg.AccountTo, arg.Amount)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.AccountFrom,
		&i.AccountTo,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
