environment: production
deploy:
  replicas: 1
  image:
    repo: 539247467338.dkr.ecr.eu-central-1.amazonaws.com/bank-api
    tag: latest
  port: 3000
service:
  port: 80
domain: vlapeka.click
serviceAccount:
  name: external-secrets-sa
  arn: arn:aws:iam::539247467338:role/bank-api-external-secrets-role
