apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api-deployment
  labels:
    app: bank-api
spec:
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
    spec:
      imagePullSecrets:
      - name: ecr-secret
      initContainers:
      - name: wait-for-postgres
        image: alpine
        command:
        - sh
        - -c
        - until nc -z {{ .Values.postgres.serviceName }} 5432; do echo "Waiting for Postgres..."; sleep 2; done
      containers:
      - name: bank-api
        image: {{ .Values.deploy.image }}
        ports:
        - containerPort: {{ .Values.deploy.port }}
        env:
        - name: POSTGRES_URL
          value: {{ .Values.deploy.postgresUrl }}
        - name: APP_PORT
          value: "{{ .Values.deploy.port }}"
        - name: JWT_SECRET_KEY
          value: {{ .Values.deploy.jwtSecret }}