apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app: {{ .Release.Name }}
    spec:
{{- if eq .Values.environment "development" }}
      imagePullSecrets:
      - name: ecr-secret
      initContainers:
      - name: wait-for-postgres
        image: alpine
        command:
        - sh
        - -c
        - until nc -z {{ .Values.postgres.name }}-service 5432; do echo "Waiting for Postgres..."; sleep 2; done
{{- end }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.deploy.image.repo }}:{{ .Values.deploy.image.tag }}
        ports:
        - containerPort: {{ .Values.deploy.port }}
        env:
        - name: APP_PORT
          value: "{{ .Values.deploy.port }}"
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-secret