apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  namespace: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      namespace: {{ .Values.appName }}
      labels:
        app: {{ .Values.appName }}
    spec:
      imagePullSecrets:
      - name: ecr-secret
      initContainers:
      - name: wait-for-postgres
        image: alpine
        command:
        - sh
        - -c
        - until nc -z {{ .Values.postgres.name }}-service 5432; do echo "Waiting for Postgres..."; sleep 2; done
      containers:
      - name: bank-api
        image: {{ .Values.deploy.image }}
        ports:
        - containerPort: {{ .Values.deploy.port }}
        env:
        - name: APP_PORT
          value: "{{ .Values.deploy.port }}"
        envFrom:
        - secretRef:
            name: bank-api-secret