{{- if eq .Values.environment "development" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}-deploy
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      nodeName: node02
      containers:
      - name: {{ .Values.postgres.name }}
        image: {{ .Values.postgres.name }}:17-alpine
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database }}
        ports:
        - containerPort: {{ .Values.postgres.port }}
        volumeMounts:
        - name: db-store
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-store
        hostPath:
          path: /data/postgres
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}

{{- end }}
