{{- if .Values.postgres.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    app: bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17-alpine
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.postgres.username }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.postgres.password }}"
        - name: POSTGRES_DB
          value: "{{ .Values.postgres.database }}"
        ports:
        - containerPort: {{ .Values.postgres.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: bank-api
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}

{{- end }}
