{{- if eq .Values.environment "development" }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_URL: {{ .Values.secret.postgresUrl | b64enc | quote }}
  JWT_SECRET_KEY: {{ .Values.secret.jwtSecret | b64enc | quote }}

{{- else }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.arn | quote }}

---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-ssm
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: kube-system

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: {{ .Release.Name }}-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_URL
      remoteRef:
        key: /bank-api-db/db_url
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: /bank-api-jwt-secret/jwt-secret-key

{{- end }}
