// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"
)

type Account struct {
	ID       int64
	Owner    string
	Currency string
	// should be positive
	Balance   int64
	CreatedAt time.Time
}

type Entry struct {
	ID        int64
	AccountID int64
	Amount    int64
	CreatedAt time.Time
}

type Transfer struct {
	ID          int64
	AccountFrom int64
	AccountTo   int64
	// should be positive
	Amount    int64
	CreatedAt time.Time
}
