// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"
)

type Account struct {
	ID       int64  `json:"id"`
	Currency string `json:"currency"`
	// should be positive
	Balance   int64     `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
	UserID    int64     `json:"user_id"`
}

type Entry struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"account_id"`
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfer struct {
	ID          int64 `json:"id"`
	AccountFrom int64 `json:"account_from"`
	AccountTo   int64 `json:"account_to"`
	// should be positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID                int64     `json:"id"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	HashedPassword    string    `json:"hashed_password"`
	PasswordChangesAt time.Time `json:"password_changes_at"`
	CreatedAt         time.Time `json:"created_at"`
}
