name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: root
          POSTGRES_DB: simple_bank_test
          POSTGRES_PASSWORD: 1234
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: go build -v ./...

      - name: Install migrate
        run: |
          go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432; do echo "Waiting for Postgres..."; sleep 3; done


      - name: Migrate
        run: |
          migrate -path storage/migrations -database "postgres://root:1234@localhost:5432/simple_bank_test?sslmode=disable" up

      - name: Test
        run: make test
